name: CI/CD Pipeline

on:
  push:
    branches: ["main", "feature/*"]
  pull_request:
    branches: ["main"]

jobs:

  basic-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies (Pytest & App requirements)
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install -r requirements.txt
        working-directory: ./vote 

      - name: Run Pytest commands
        run: pytest
        working-directory: ./vote

  # docker-cd:
  #   name: Docker Build and Push
  #   runs-on: ubuntu-latest
    
  #   needs: basic-test 
  #   if: github.event_name == 'push' 

  #   steps:
  #     - name: Checkout repository code
  #       uses: actions/checkout@v4

  #     # Langkah 1: Login ke Docker Hub menggunakan Secrets
  #     - name: Login to Docker Hub
  #       # Action untuk melakukan Docker Login
  #       uses: docker/login-action@v3
  #       with:
  #         username: ${{ secrets.DOCKER_USERNAME }}
  #         password: ${{ secrets.DOCKER_PASSWORD }}
          
  #     - name: Build and Push Vote App Image
  #       uses: docker/build-push-action@v5
  #       with:
  #         context: ./vote 
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/voting-app-vote:latest
