name: CI Pipeline Basic

on:
  push:
    branches: ["main", "feature/*"]
  pull_request:
    branches: ["main"]

jobs:
  basic-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4 # Menggunakan versi terbaru

      # Langkah 1: Setup Python Environment
      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Pindah ke direktori vote untuk semua operasi terkait Python
      - name: Install dependencies (Pytest & App requirements)
        run: |
          python -m pip install --upgrade pip
          # Instal Pytest untuk testing
          pip install pytest
          # Instal semua dependencies yang dibutuhkan app.py
          pip install -r requirements.txt
        working-directory: ./vote 

      # Langkah 2: Menjalankan Pytest
      - name: Run Pytest commands
        # Pytest akan mencari file test secara otomatis di direktori 'vote'
        run: pytest
        working-directory: ./vote
